### ISSUE TITLE
Meta Replacement does not work as intended

### ISSUE THREAD

**Issue by RealAkito** [crashdemons/DisplayItem-Spigot#3]
Hey there,

Great plugin here, though I have found out that "metareplacement" does not work as intended.

When I sent [I], it should returned the "item display", but instead returned [item].

If you need any more information, please do tell.

Thanks in advance.

![image](https://user-images.githubusercontent.com/44841395/78711569-24ce4b00-7952-11ea-952c-78af6b3f3288.png)

**Comment by RealAkito** [comment]
I have as well tested this plugin on 1.15.2 server as well, it is working as intended, apart from meta replacement as I've addressed on [here](https://github.com/crashdemons/DisplayItem-Spigot/issues/3#issue-596102475). You might want to update the repository description.

**Comment by crashdemons** [comment]
The wiki should be clearer but when you post [I] (or your 'metareplacement' value) it should post in chat your replacement string [i] (or your 'replacement' value).

It was intended so you could use it to tell people what to post.  

----
So if replacement is [item]
and metareplacement is [I]

then [I] should display [item]
and [item] (separately) should display [your held item name here]

Sorry for the late reply, I didn't get a notification for the issue.

**Comment by crashdemons** [comment]
I've made changes to the default config and the documentation. Hopefully this should be clearer as to the purpose?

https://github.com/crashdemons/DisplayItem-Spigot/wiki/Configuration
https://github.com/crashdemons/DisplayItem-Spigot/blob/master/src/main/resources/config.yml#L2

**Comment by RealAkito** [comment]
> I've made changes to the default config and the documentation. Hopefully this should be clearer as to the purpose?
> 
> https://github.com/crashdemons/DisplayItem-Spigot/wiki/Configuration
> https://github.com/crashdemons/DisplayItem-Spigot/blob/master/src/main/resources/config.yml#L2

Yes it is, that's very nice of you. Thanks for developing such a great plugin that's working as intended :D. Perhaps this issue can be closed now.
